# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_trade', '0002_auto_20180714_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('holding', models.DecimalField(decimal_places=4, max_digits=10)),
                ('profit_loss_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assets', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Btc',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=10)),
                ('average', models.DecimalField(decimal_places=4, max_digits=10)),
                ('turnover', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
