# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0003_account_btc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btc',
            name='datetime',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
