# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0004_auto_20180714_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btc',
            name='turnover',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
